### PR TITLE
Less battery drain with the new HIDL based power HAL

### PR DESCRIPTION
**Pull request by dariotrombello**
Im still experimentating with this. The problem is atm that the second cpu cluster is constantly powered with 0.93v even though it isnt used. I think there is a a3xelte specific kernel needed to fix this but idk. Merge it if you want ;-D

### CODE REVIEW

**Comment by dariotrombello** [comment]
After some time i can say that the battery consumption is much better on dotOS with these patches. I havent experienced any issues with this

**Comment by danwood76** [comment]
If you are using the Exynos7580 kernel then the second CPU cluster is not even enabled (it is disabled in the device tree).

I stopped using my port of the Nexus power HAL as when the screen is off any apps run really slow and this causes audio glitches if you are playing music and sometimes gapps crashes (it also causes weird behaviour on boot).

To be honest I am getting about the same battery life with the fixed CPU governor settings I set in the RAM disk as I did in the previous balanced mode so I think the BSP power HAL is working just fine.

**Comment by dariotrombello** [comment]
screenshot_device_info_hw_20181011-205340

**Comment by dariotrombello** [comment]
Hmm.. i havent experienced gapps crashes. As i dont hear music often i also need to try it out and see why its like this

**Comment by dariotrombello** [comment]
Okay got 2 reports that gapps are crashing on dotos. I think i need to revert it too :/

**Pull request closed without merging**
