### PR TITLE
Dunno what i'm doing lol

### PR DESCRIPTION
**Pull request by dariotrombello**
Let's unleash da 1.6 ghz

### CODE REVIEW

**Comment by Borduni** [comment]
@Borduni I reply to myself lol

**Comment by ch8matt** [comment]
@Borduni ;-;

**Comment by ch8matt** [comment]
@McFy49 U pru dev

**Comment by axemre** [comment]
@McFy49 Yes

**Comment by dariotrombello** [comment]
I'm demonstrating my xml skills

**Comment by ch8matt** [comment]
@Borduni Wow can't you keep them for u ?

**Comment by axemre** [comment]
@Borduni Stop it.

**Comment by dariotrombello** [comment]
k i'll close this pr

**Comment by ch8matt** [comment]
@Borduni You must lal

**Comment by dariotrombello** [comment]
wuts lal?

**Comment by ch8matt** [comment]
@Borduni Wut u ;-;

**Comment by dariotrombello** [comment]
??

**Comment by ch8matt** [comment]
@Borduni Nvm close it

**Pull request closed without merging**
